### ISSUE TITLE
Help with Customization 

### ISSUE THREAD

**Issue by seantm22** [shadowk29/BinanceBalance#1] opened 2018-11-09 08:00 UTC
Hi I would like to discuss using this code and working with you on it need some customization do you have contact info? email me at seanmichael@vaway.com. Thanks!

**Comment by shadowk29** [comment] 2018-11-09 17:22
I sent you my coordinates. We can also discuss your feature requests here if that's easier.

**Comment by seantm22** [comment] 2018-11-09 17:36
Hi Kyle,

We are adding social trading to our platform and also rebalancing to the site so its plugin to our existing infrastructure. We are excited about your code it looks interesting will test it on our servers prior. We really appreciate your help might need some help on customization and development as we are trying to get as close to the capabilities of shrimpy.io. 

Sean Michael
www.Mosaicexchange.co
720-277-7975

**Comment by shadowk29** [comment] 2018-11-09 19:28
Interesting. Out of curiosity, how did you come across my repo?

I'm open to helping out. Bear in mind that this is a hobby for me, so development on my end goes as time permits. Let me know how your tests go and we can discuss what's feasible based on your needs.

**Comment by seantm22** [comment] 2018-11-28 06:43
Hi Kyle when would you have time to look at our code and implement your
code into our site? We had to make some adjustments to prepare. So here is
the deal I need to setup the site to do the same thing Shrimpy.io does. My
dev set the GUI into the site on test server but I need to install same
functionality in this screen you see of screenshot onto our site. We are
adding copy trading/Social trading (Follow peoples trades) like shrimpy but
this code is already being built. So if you can help I need to install your
code into our site and run it same as shrimpy model with stop loss option
if needed and maybe larger dumps so if someone wants to balance by dumping
a coin after certain percentage of profit. Whatever easiest to get started
with is great but we are on tight schedule. I have a dev to help you and
work through setup. If you can get this installed I can also probably use
you in future for many things. Do you know php?

Site name Mosaic Exchange

Sean Michael
7202777975
www.MosaicExchange.co
On Nov 9, 2018, at 1:28 PM, Kyle Briggs <notifications@github.com> wrote:

Interesting. Out of curiosity, how did you come across my repo?

I'm open to helping out. Bear in mind that this is a hobby for me, so
development on my end goes as time permits. Let me know how your tests go
and we can discuss what's feasible based on your needs.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/shadowk29/BinanceBalance/issues/1#issuecomment-437468990>,
or mute the thread

**Comment by shadowk29** [comment] 2018-11-28 14:28
I should have been more clear in my earlier post - I am open to helping implement new features into this repo, time permitting, but integration into your site is on you guys. If your web dev has specific questions they are welcome to post them here and I might be able to answer, but I don't have much experience as a web developer so no guarantees there.

As far as the features you want, I could probably implement a simple stop loss/take profit mechanism sometime in Q1 2019, but I would have to implement USDT trading first, since there's not much point to a stop-loss selling to BTC. 

Copy trading would have to be implemented on your end, since the app here does not interact with anyone else (by design). Copy trading in general strikes me as a bad idea: if you are copying someone else, what's to stop them using your funds to do a P&D?

Bear in mind that I only contribute as a volunteer to open source projects, so if you want advice on specific parts of your code you will need to make them open source.

I don't see a screenshot in your post.

Cheers,
Kyle

**Comment by shadowk29** [comment] 2019-02-21 15:12
Closing since it seems that you are not interested in pursuing this further.

**Closed as completed by shadowk29** 2019-02-21 15:12 UTC
